AWSTemplateFormatVersion: "2010-09-09"
Description: This template will create the S3 bucket that will host our Vue application
Resources:
  VueAppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mybucketstack
      Tags:
        - Key: Application Name
          Value: VueApp
        - Key: Company
          Value: Otsiaws
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
  
